### ISSUE TITLE
数据多了会很卡

### ISSUE THREAD

**Issue by realicing** [SmallStoneSK/react-native-expandable-list#1]
比如data数据如下：
const data = Array.from({length: 100}).map((item,index)=>({
            groupHeaderData: {title: 'Settings'},
            groupListData: ['Fill Beer', 'Adjust', 'Alarm']
        }))
滑动的时候没觉得什么，但是打开或关闭子项时就会很卡

**Comment by SmallStoneSK** [comment]
@realicing 
你是用的flatList渲染吗？scrollview渲染的应该会卡，flatList应该会好点的。

**Comment by leo4developer** [comment]
用flatList也很卡，30多条数据就不行了
